services:
  backend:
    build: ./backend_django/quizApplication
    ports:
      - "8000:8000"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  web:
    build: ./quiz-application
    ports:
      - "3000:3000"