# Generated by Django 3.2.8 on 2023-01-31 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fristName',
            new_name='firstName',
        ),
    ]
