# Generated by Django 3.2.8 on 2023-01-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizeID', models.IntegerField()),
                ('question', models.CharField(max_length=256)),
                ('quizeOption1', models.CharField(max_length=256)),
                ('quizeOption2', models.CharField(max_length=256)),
                ('quizeOption3', models.CharField(max_length=256)),
                ('quizeOption4', models.CharField(max_length=256)),
                ('quizeAnswer', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizeID', models.IntegerField()),
                ('quizeName', models.CharField(max_length=256)),
                ('quizeCreator', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('phoneNo', models.IntegerField()),
                ('email', models.CharField(max_length=256)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
