# Generated by Django 3.2.8 on 2023-01-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(max_length=256)),
                ('quizQuestion', models.CharField(max_length=256)),
                ('quizAnswer1', models.CharField(max_length=256)),
                ('quizAnswer2', models.CharField(max_length=256)),
                ('quizAnswer3', models.CharField(max_length=256)),
                ('quizAnswer4', models.CharField(max_length=256)),
                ('correctAnswer', models.CharField(max_length=256)),
                ('questionScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='quizSocre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(max_length=256)),
                ('userEmail', models.CharField(max_length=256)),
                ('quizScore', models.IntegerField()),
                ('quizMaxScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fristName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
