# Generated by Django 3.2.8 on 2023-02-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quizSocre',
            new_name='quizScore',
        ),
    ]
